---
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "108.0"
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.34.0"
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            bundle exec rake spec
